Repository CN-missemi/CN_missemi, pull requests merged in 2021-03, with the labels that each got.

#28 L_ch2_A179
  ch2/[1-478]major.sub
  ch2/[1-478]minor.sub
Labels: 新增时间轴 / Add Timeline

#32 Review: ch2 ksyx 558-756
  ch2/[558-756]CHN.txt
Labels: 翻译校对 / Checks

#31 [TRANSLATION] review
  ch2/[558-756]CHN.txt
Labels: 翻译校对 / Checks

#24 T_ch2_GNAQ
  ch2/[756-966]CHN.txt
Labels: 新增翻译 / Add Translation, 需要时间轴 / Need Timeline
